INSERT INTO imecare_procedimento VALUES ('2,5-Hexanodiona Urinário');
INSERT INTO imecare_procedimento VALUES ('3-Alfa Androstanediol Glicuronídeo');
INSERT INTO imecare_procedimento VALUES ('5-Nucleotidase');
INSERT INTO imecare_procedimento VALUES ('Acetona');
INSERT INTO imecare_procedimento VALUES ('Ácido Mandélico');
INSERT INTO imecare_procedimento VALUES ('Ácido Acetilcolinesterase Eritrocitária');
INSERT INTO imecare_procedimento VALUES ('Ácido Anti-Fosfolipídios IgG');
INSERT INTO imecare_procedimento VALUES ('Ácido Cítrico - Sangue');
INSERT INTO imecare_procedimento VALUES ('Ácido Cítrico - Urina');
INSERT INTO imecare_procedimento VALUES ('Ácido Delta Aminolevulínico (ALA-U)');
INSERT INTO imecare_procedimento VALUES ('Ácido Fólico');
INSERT INTO imecare_procedimento VALUES ('Ácido Fólico Eritrocitário');
INSERT INTO imecare_procedimento VALUES ('Ácido Hipúrico');
INSERT INTO imecare_procedimento VALUES ('Ácido Lático (Lactato)');
INSERT INTO imecare_procedimento VALUES ('Ácido Metil Hipúrico');
INSERT INTO imecare_procedimento VALUES ('Ácido Oxálico (Oxalato)');
INSERT INTO imecare_procedimento VALUES ('Ácido Transmucônico - Urina');
INSERT INTO imecare_procedimento VALUES ('Ácido Tricloroacético (ATA)');
INSERT INTO imecare_procedimento VALUES ('Ácido Úrico');
INSERT INTO imecare_procedimento VALUES ('Ácido Valpróico');
INSERT INTO imecare_procedimento VALUES ('Ácido Vanilmandélico (VMA)');
INSERT INTO imecare_procedimento VALUES ('ACTH - Hormônio Adrenocorticotrófico');
INSERT INTO imecare_procedimento VALUES ('Açúcares Redutores');
INSERT INTO imecare_procedimento VALUES ('Adenosina Deaminase (ADA)');
INSERT INTO imecare_procedimento VALUES ('Adenovírus');
INSERT INTO imecare_procedimento VALUES ('Adenovírus IgG');
INSERT INTO imecare_procedimento VALUES ('Adenovírus IgM');
INSERT INTO imecare_procedimento VALUES ('Água - Análise Microbiológica');
INSERT INTO imecare_procedimento VALUES ('Albumina Plasmática');
INSERT INTO imecare_procedimento VALUES ('Aldolase');
INSERT INTO imecare_procedimento VALUES ('Aldosterona');
INSERT INTO imecare_procedimento VALUES ('Aldosterona Urinária - 24h');
INSERT INTO imecare_procedimento VALUES ('Alfa-1-Antitripsina');
INSERT INTO imecare_procedimento VALUES ('Alfa-1-Glicoproteína Ácida');
INSERT INTO imecare_procedimento VALUES ('Alfa-1-Antitripsina Fecal');
INSERT INTO imecare_procedimento VALUES ('Alfa Fetoproteína');
INSERT INTO imecare_procedimento VALUES ('Alumínio (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Alumínio (Urina)');
INSERT INTO imecare_procedimento VALUES ('Amebíase - Sorologia');
INSERT INTO imecare_procedimento VALUES ('Amicacina - Dosagem');
INSERT INTO imecare_procedimento VALUES ('Amilase (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Amilasúria (Urina 24h)');
INSERT INTO imecare_procedimento VALUES ('Aminoácidos (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Aminoácidos (Urina)');
INSERT INTO imecare_procedimento VALUES ('Amônia');
INSERT INTO imecare_procedimento VALUES ('Análise Físico-Química de Cálculo Renal');
INSERT INTO imecare_procedimento VALUES ('ANCA - Neutrófilos Anti-Anca');
INSERT INTO imecare_procedimento VALUES ('Androstenediona');
INSERT INTO imecare_procedimento VALUES ('Anfetaminas (DAU-A)');
INSERT INTO imecare_procedimento VALUES ('Antiestreptolisina-O (ASLO)');
INSERT INTO imecare_procedimento VALUES ('Anti HTLV 1/2 - Anticorpos');
INSERT INTO imecare_procedimento VALUES ('Anti LDL - Anticorpos Anti-LDL Oxidase IgG');
INSERT INTO imecare_procedimento VALUES ('Anti Músculo Liso');
INSERT INTO imecare_procedimento VALUES ('Anti Plaquetário');
INSERT INTO imecare_procedimento VALUES ('Anti SM');
INSERT INTO imecare_procedimento VALUES ('Anti SSA / RO');
INSERT INTO imecare_procedimento VALUES ('Anti SSB / LA');
INSERT INTO imecare_procedimento VALUES ('Anti Tireoglobulinas');
INSERT INTO imecare_procedimento VALUES ('Antibiograma (Fezes)');
INSERT INTO imecare_procedimento VALUES ('Antibiograma (Urina)');
INSERT INTO imecare_procedimento VALUES ('Anticoagulante Circulante e Lúpico');
INSERT INTO imecare_procedimento VALUES ('Anticorpos IgG Anti Beta-2-Glicoproteína');
INSERT INTO imecare_procedimento VALUES ('Anticorpos IgG Anti Fosfatidilserina');
INSERT INTO imecare_procedimento VALUES ('Anticorpos IgM Anti Beta-2-Glicoproteína');
INSERT INTO imecare_procedimento VALUES ('Anticorpos IgM Fosfatidilserina');
INSERT INTO imecare_procedimento VALUES ('Antidepressivos Tricíclicos');
INSERT INTO imecare_procedimento VALUES ('Antígeno Austrália (HBsAg)');
INSERT INTO imecare_procedimento VALUES ('Antígeno E (HBeAg)');
INSERT INTO imecare_procedimento VALUES ('Anti-HIV 1/2 por Western-Blot');
INSERT INTO imecare_procedimento VALUES ('Antioxidantes Totais');
INSERT INTO imecare_procedimento VALUES ('Antitrombina III');
INSERT INTO imecare_procedimento VALUES ('Apolipoproteína A');
INSERT INTO imecare_procedimento VALUES ('Apolipoproteína B');
INSERT INTO imecare_procedimento VALUES ('Arsênio (Urina)');
INSERT INTO imecare_procedimento VALUES ('Aspergillus por I.D.R.');
INSERT INTO imecare_procedimento VALUES ('Anti-Fosfolipídios IgM');
INSERT INTO imecare_procedimento VALUES ('Barbitúricos DAU - B');
INSERT INTO imecare_procedimento VALUES ('Beta 2 Microglobulinas (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Beta 2 Microglobulinas (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Beta Caroteno');
INSERT INTO imecare_procedimento VALUES ('Bilirrubinas');
INSERT INTO imecare_procedimento VALUES ('Brucelose');
INSERT INTO imecare_procedimento VALUES ('CA-72.4');
INSERT INTO imecare_procedimento VALUES ('CA 125');
INSERT INTO imecare_procedimento VALUES ('CA-15.3');
INSERT INTO imecare_procedimento VALUES ('CA-19.9');
INSERT INTO imecare_procedimento VALUES ('Cadeia Kappa (Cadeias Leve) - Urina');
INSERT INTO imecare_procedimento VALUES ('Cadeia Kappa (Cadeias Leves) - Soro');
INSERT INTO imecare_procedimento VALUES ('Cadeia Lambda (Cadeia Leves) - Soro');
INSERT INTO imecare_procedimento VALUES ('Cadeia Lambda (Cadeias Leves) - Urina');
INSERT INTO imecare_procedimento VALUES ('Cádmio (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Cádmio (Urina)');
INSERT INTO imecare_procedimento VALUES ('Cálcio');
INSERT INTO imecare_procedimento VALUES ('Cálcio Eritrocitário');
INSERT INTO imecare_procedimento VALUES ('Cálcio Iônico');
INSERT INTO imecare_procedimento VALUES ('Calcitonina');
INSERT INTO imecare_procedimento VALUES ('Calciúria (Urina 12 H)');
INSERT INTO imecare_procedimento VALUES ('Calciúria (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('Calciúria (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Capacidade de Fixação de Ferro');
INSERT INTO imecare_procedimento VALUES ('Capacidade Latente LIgAção Ferro');
INSERT INTO imecare_procedimento VALUES ('Carbamazepina');
INSERT INTO imecare_procedimento VALUES ('Carboxihemoglobina');
INSERT INTO imecare_procedimento VALUES ('Cardiolipina IgA (Anticorpos)');
INSERT INTO imecare_procedimento VALUES ('Cardiolipina IgG (Anticorpos)');
INSERT INTO imecare_procedimento VALUES ('Cardiolipina IgM (Anticorpos)');
INSERT INTO imecare_procedimento VALUES ('Carga Viral para HIV');
INSERT INTO imecare_procedimento VALUES ('Cariótipo');
INSERT INTO imecare_procedimento VALUES ('Catecolaminas - Frações (Plasma)');
INSERT INTO imecare_procedimento VALUES ('Catecolaminas Fracionadas');
INSERT INTO imecare_procedimento VALUES ('Catecolaminas Totais');
INSERT INTO imecare_procedimento VALUES ('Caxumba IgG');
INSERT INTO imecare_procedimento VALUES ('Caxumba IgM');
INSERT INTO imecare_procedimento VALUES ('CCP - Anti');
INSERT INTO imecare_procedimento VALUES ('CD4');
INSERT INTO imecare_procedimento VALUES ('CD4 - 8 - 3');
INSERT INTO imecare_procedimento VALUES ('CD8');
INSERT INTO imecare_procedimento VALUES ('CEA (Antígeno Carcino-Embriônico)');
INSERT INTO imecare_procedimento VALUES ('Células LE');
INSERT INTO imecare_procedimento VALUES ('Células LE - Hargraves');
INSERT INTO imecare_procedimento VALUES ('Ceruloplasmina');
INSERT INTO imecare_procedimento VALUES ('Cetonemia');
INSERT INTO imecare_procedimento VALUES ('Cetonuria');
INSERT INTO imecare_procedimento VALUES ('Chagas (Hemaglutinação)');
INSERT INTO imecare_procedimento VALUES ('Chagas IgG');
INSERT INTO imecare_procedimento VALUES ('Chagas IgG (Hemaglutinação)');
INSERT INTO imecare_procedimento VALUES ('Chagas IgM');
INSERT INTO imecare_procedimento VALUES ('Chagas IgM (Hemaglutinação)');
INSERT INTO imecare_procedimento VALUES ('Chagas por Elisa');
INSERT INTO imecare_procedimento VALUES ('Chagas por Machado Guerreiro');
INSERT INTO imecare_procedimento VALUES ('Chlamydia - Pesquisa por PCR');
INSERT INTO imecare_procedimento VALUES ('Chlamydia Pneumoniae IGG');
INSERT INTO imecare_procedimento VALUES ('Chlamydia Pneumoniae IgM');
INSERT INTO imecare_procedimento VALUES ('Chlamydia Trachomatis IgA');
INSERT INTO imecare_procedimento VALUES ('Chlamydia Trachomatis IgG');
INSERT INTO imecare_procedimento VALUES ('Chlamydia Trachomatis IgM');
INSERT INTO imecare_procedimento VALUES ('Chlamydia Trachomatis-AG (Diversos)');
INSERT INTO imecare_procedimento VALUES ('Chlamydia Trachomatis-AG (Homem)');
INSERT INTO imecare_procedimento VALUES ('Chlamydia Trachomatis-AG (Mulher)');
INSERT INTO imecare_procedimento VALUES ('Chumbo (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Chumbo (Urina)');
INSERT INTO imecare_procedimento VALUES ('Cisticercose');
INSERT INTO imecare_procedimento VALUES ('Cistina');
INSERT INTO imecare_procedimento VALUES ('Citológico Líquido Sinovial');
INSERT INTO imecare_procedimento VALUES ('Citomegalovírus - Antigenemia');
INSERT INTO imecare_procedimento VALUES ('Citomegalovírus IgG');
INSERT INTO imecare_procedimento VALUES ('Citomegalovírus IgG (Elfa)');
INSERT INTO imecare_procedimento VALUES ('Citomegalovírus IgG no Líquor');
INSERT INTO imecare_procedimento VALUES ('Citomegalovírus IgM');
INSERT INTO imecare_procedimento VALUES ('Citomegalovírus IgM (Elfa)');
INSERT INTO imecare_procedimento VALUES ('Citomegalovírus IgM no Líquor');
INSERT INTO imecare_procedimento VALUES ('Clobazam');
INSERT INTO imecare_procedimento VALUES ('Clorazepan');
INSERT INTO imecare_procedimento VALUES ('Cloro - Cloretos');
INSERT INTO imecare_procedimento VALUES ('Cloro (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('CO2 - Reserva Alcalina');
INSERT INTO imecare_procedimento VALUES ('Cobre (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Cobre (Urina 24 Hrs)');
INSERT INTO imecare_procedimento VALUES ('Cobre (Urina)');
INSERT INTO imecare_procedimento VALUES ('Cobre Eritrocitário');
INSERT INTO imecare_procedimento VALUES ('Cocaína (Imunocromatografia)');
INSERT INTO imecare_procedimento VALUES ('Colesterol HDL');
INSERT INTO imecare_procedimento VALUES ('Colesterol LDL');
INSERT INTO imecare_procedimento VALUES ('Colesterol LDL Peroxidase');
INSERT INTO imecare_procedimento VALUES ('Colesterol Total');
INSERT INTO imecare_procedimento VALUES ('Colesterol VLDL');
INSERT INTO imecare_procedimento VALUES ('Coliformes Fecais');
INSERT INTO imecare_procedimento VALUES ('Colinesterase');
INSERT INTO imecare_procedimento VALUES ('Complemento C-1 Q');
INSERT INTO imecare_procedimento VALUES ('Complemento C1 S Esterase Inibidor');
INSERT INTO imecare_procedimento VALUES ('Complemento C2 (C-2)');
INSERT INTO imecare_procedimento VALUES ('Complemento C3');
INSERT INTO imecare_procedimento VALUES ('Complemento C4');
INSERT INTO imecare_procedimento VALUES ('Complemento Total CH-100');
INSERT INTO imecare_procedimento VALUES ('Complemento Total CH-50');
INSERT INTO imecare_procedimento VALUES ('Contagem de Piócitos');
INSERT INTO imecare_procedimento VALUES ('Coombs Direto');
INSERT INTO imecare_procedimento VALUES ('Coombs Indireto');
INSERT INTO imecare_procedimento VALUES ('Coprocultura');
INSERT INTO imecare_procedimento VALUES ('Coproporfirinas');
INSERT INTO imecare_procedimento VALUES ('Cortisol (08:00h)');
INSERT INTO imecare_procedimento VALUES ('Cortisol (16:00h)');
INSERT INTO imecare_procedimento VALUES ('Cortisol (Pool)');
INSERT INTO imecare_procedimento VALUES ('Cortisol (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Cortisol Urinário (Livre)');
INSERT INTO imecare_procedimento VALUES ('Corynebacteriom Minurissimum');
INSERT INTO imecare_procedimento VALUES ('CPK-Creatinofosfoquinase');
INSERT INTO imecare_procedimento VALUES ('Creatinofosfoquinase-MB (CPK-MB)');
INSERT INTO imecare_procedimento VALUES ('Creatinina');
INSERT INTO imecare_procedimento VALUES ('Creatininúria (Urina 12 H)');
INSERT INTO imecare_procedimento VALUES ('Creatininúria (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('Creatininúria (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Crioaglutininas');
INSERT INTO imecare_procedimento VALUES ('Crioglobulinas');
INSERT INTO imecare_procedimento VALUES ('Cromo (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Cromo (Urina)');
INSERT INTO imecare_procedimento VALUES ('Curva de Insulina');
INSERT INTO imecare_procedimento VALUES ('Curva de Lactose');
INSERT INTO imecare_procedimento VALUES ('Curva Glicêmica');
INSERT INTO imecare_procedimento VALUES ('Curva Glicêmica (2 dosagens)');
INSERT INTO imecare_procedimento VALUES ('D-Dímeros');
INSERT INTO imecare_procedimento VALUES ('Dehidroepiandrosterona (DHEA)');
INSERT INTO imecare_procedimento VALUES ('Dehidrotestosterona');
INSERT INTO imecare_procedimento VALUES ('Dengue IgG');
INSERT INTO imecare_procedimento VALUES ('Dengue IgM');
INSERT INTO imecare_procedimento VALUES ('Depuração Creatinina Endógena (DCE)');
INSERT INTO imecare_procedimento VALUES ('Desidrogenase');
INSERT INTO imecare_procedimento VALUES ('Dez. Cetosteróide - 17 KS');
INSERT INTO imecare_procedimento VALUES ('Dez. Hidroxicorticosteróide - 17 OH');
INSERT INTO imecare_procedimento VALUES ('Dez. Hidroxiprogesterona');
INSERT INTO imecare_procedimento VALUES ('Diazepan');
INSERT INTO imecare_procedimento VALUES ('Difenilhidantoina (Fenitoína)');
INSERT INTO imecare_procedimento VALUES ('Digitoxina');
INSERT INTO imecare_procedimento VALUES ('Digoxina');
INSERT INTO imecare_procedimento VALUES ('Dismorfismo Hemático');
INSERT INTO imecare_procedimento VALUES ('DNA, Anti');
INSERT INTO imecare_procedimento VALUES ('Eletroforese de Hemoglobina');
INSERT INTO imecare_procedimento VALUES ('Endomísio - Anticorpos');
INSERT INTO imecare_procedimento VALUES ('Endomísio IgA - Anticorpos');
INSERT INTO imecare_procedimento VALUES ('Eosinófilos, Pesquisa de');
INSERT INTO imecare_procedimento VALUES ('EPF (Exame Parasitológico de Fezes)');
INSERT INTO imecare_procedimento VALUES ('Epstein Barr IgM');
INSERT INTO imecare_procedimento VALUES ('Epstein Barr IgG');
INSERT INTO imecare_procedimento VALUES ('Eritrograma');
INSERT INTO imecare_procedimento VALUES ('Eritropoetina');
INSERT INTO imecare_procedimento VALUES ('Erros Inatos do Metabolismo');
INSERT INTO imecare_procedimento VALUES ('Espermatozóide, Anticorpo Anti');
INSERT INTO imecare_procedimento VALUES ('Espermocultura');
INSERT INTO imecare_procedimento VALUES ('Espermograma');
INSERT INTO imecare_procedimento VALUES ('Espermograma Após Vasectomia');
INSERT INTO imecare_procedimento VALUES ('Esquitossomose');
INSERT INTO imecare_procedimento VALUES ('Estradiol');
INSERT INTO imecare_procedimento VALUES ('Estradiol - 17 Beta');
INSERT INTO imecare_procedimento VALUES ('Estradiol Pool');
INSERT INTO imecare_procedimento VALUES ('Estriol');
INSERT INTO imecare_procedimento VALUES ('Estriol Urinário');
INSERT INTO imecare_procedimento VALUES ('Etanol - Álcool Etílico');
INSERT INTO imecare_procedimento VALUES ('Exame Qualitativo de Urina');
INSERT INTO imecare_procedimento VALUES ('Exame Qualitativo de Urina (1º Jato)');
INSERT INTO imecare_procedimento VALUES ('FAN (Fator Anti Núcleo)');
INSERT INTO imecare_procedimento VALUES ('Fator DU');
INSERT INTO imecare_procedimento VALUES ('Fator II');
INSERT INTO imecare_procedimento VALUES ('Fator IX');
INSERT INTO imecare_procedimento VALUES ('Fator Reumatóide');
INSERT INTO imecare_procedimento VALUES ('Fator RH');
INSERT INTO imecare_procedimento VALUES ('Fator Von Willebrand Fator V');
INSERT INTO imecare_procedimento VALUES ('Fator V - Leiden');
INSERT INTO imecare_procedimento VALUES ('Fator VII');
INSERT INTO imecare_procedimento VALUES ('Fator VIII');
INSERT INTO imecare_procedimento VALUES ('Fator X');
INSERT INTO imecare_procedimento VALUES ('Fator XII');
INSERT INTO imecare_procedimento VALUES ('Fator XIII');
INSERT INTO imecare_procedimento VALUES ('Fenilalanina na Urina');
INSERT INTO imecare_procedimento VALUES ('Fenilanina no Soro');
INSERT INTO imecare_procedimento VALUES ('Fenobarbital');
INSERT INTO imecare_procedimento VALUES ('Fenol');
INSERT INTO imecare_procedimento VALUES ('Ferritina');
INSERT INTO imecare_procedimento VALUES ('Ferro');
INSERT INTO imecare_procedimento VALUES ('Ferro (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Fibrinogênio');
INSERT INTO imecare_procedimento VALUES ('Fluoreto');
INSERT INTO imecare_procedimento VALUES ('Fluoxetina');
INSERT INTO imecare_procedimento VALUES ('Formaldeído (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Fosfatase Ácida Prostática');
INSERT INTO imecare_procedimento VALUES ('Fosfatase Ácida Total');
INSERT INTO imecare_procedimento VALUES ('Fosfatase Alcalina');
INSERT INTO imecare_procedimento VALUES ('Fosfatase Alcalina Fração Óssea');
INSERT INTO imecare_procedimento VALUES ('Fosfatase Alcalina Leucocitária');
INSERT INTO imecare_procedimento VALUES ('Fosfatúria (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('Fosfatúria (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Fósforo');
INSERT INTO imecare_procedimento VALUES ('Fragilidade Osmótica (Curva)');
INSERT INTO imecare_procedimento VALUES ('Frutosamina');
INSERT INTO imecare_procedimento VALUES ('Frutose (Esperma)');
INSERT INTO imecare_procedimento VALUES ('FSH (Hormônio Folículo Estimulante)');
INSERT INTO imecare_procedimento VALUES ('FSH Pool');
INSERT INTO imecare_procedimento VALUES ('FTA-ABS-IgG (Sífilis)');
INSERT INTO imecare_procedimento VALUES ('FTA-ABS-IgM (Sífilis)');
INSERT INTO imecare_procedimento VALUES ('Gama Glutamil Transferase (Gama GT)');
INSERT INTO imecare_procedimento VALUES ('Gastrina');
INSERT INTO imecare_procedimento VALUES ('Gentamicina');
INSERT INTO imecare_procedimento VALUES ('Giardia IgG-Anti Anticorpos');
INSERT INTO imecare_procedimento VALUES ('Giardia IgM-Anti Anticorpos');
INSERT INTO imecare_procedimento VALUES ('Gliandina IgM-Anti Anticorpos');
INSERT INTO imecare_procedimento VALUES ('Glicose');
INSERT INTO imecare_procedimento VALUES ('Glicose (horário)');
INSERT INTO imecare_procedimento VALUES ('Glicose 1 Hora Após');
INSERT INTO imecare_procedimento VALUES ('Glicose-6-Fosfato Desidrogenase');
INSERT INTO imecare_procedimento VALUES ('Glicose Pós Almoco');
INSERT INTO imecare_procedimento VALUES ('Glicose Pós Café');
INSERT INTO imecare_procedimento VALUES ('Glicose Pós-Prandial');
INSERT INTO imecare_procedimento VALUES ('Glicosúria');
INSERT INTO imecare_procedimento VALUES ('Glicosúria Amostra');
INSERT INTO imecare_procedimento VALUES ('Globulina de LIgAção da Tiroxina (TBG)');
INSERT INTO imecare_procedimento VALUES ('Globulinas');
INSERT INTO imecare_procedimento VALUES ('Gordura Fecal');
INSERT INTO imecare_procedimento VALUES ('Gordura Fecal, Pesquisa');
INSERT INTO imecare_procedimento VALUES ('Grupo Sanguíneo');
INSERT INTO imecare_procedimento VALUES ('Haptoglobina');
INSERT INTO imecare_procedimento VALUES ('HBc IgM, Anti');
INSERT INTO imecare_procedimento VALUES ('HBc total, Anti');
INSERT INTO imecare_procedimento VALUES ('HBDH');
INSERT INTO imecare_procedimento VALUES ('HBe total, Anti');
INSERT INTO imecare_procedimento VALUES ('HBs, Anti');
INSERT INTO imecare_procedimento VALUES ('HCG Quantitativo');
INSERT INTO imecare_procedimento VALUES ('HCG Semi-quantitativo');
INSERT INTO imecare_procedimento VALUES ('HCV, Anti');
INSERT INTO imecare_procedimento VALUES ('Helicobacter Pylori');
INSERT INTO imecare_procedimento VALUES ('Helicobacter Pylori (Fezes)');
INSERT INTO imecare_procedimento VALUES ('Helicobacter Pylori (IGG)');
INSERT INTO imecare_procedimento VALUES ('Helicobacter Pylori (Teste Respiratório)');
INSERT INTO imecare_procedimento VALUES ('Helmintos, Exame de Fragmentos');
INSERT INTO imecare_procedimento VALUES ('Hemaglutinação para Rubéola');
INSERT INTO imecare_procedimento VALUES ('Hematócrito');
INSERT INTO imecare_procedimento VALUES ('Hemaglutinação para Sífilis');
INSERT INTO imecare_procedimento VALUES ('Hemocultura');
INSERT INTO imecare_procedimento VALUES ('Hemoglobina');
INSERT INTO imecare_procedimento VALUES ('Hemoglobina - F (Fetal)');
INSERT INTO imecare_procedimento VALUES ('Hemoglobina A2');
INSERT INTO imecare_procedimento VALUES ('Hemoglobina Glicosilada A1C');
INSERT INTO imecare_procedimento VALUES ('Hemoglobina H');
INSERT INTO imecare_procedimento VALUES ('Hemograma');
INSERT INTO imecare_procedimento VALUES ('Hepatite B - Genotipagem');
INSERT INTO imecare_procedimento VALUES ('Hepatite B por P.C.R. - Quantificação');
INSERT INTO imecare_procedimento VALUES ('Hepatite B por P.C.R. - Detecção');
INSERT INTO imecare_procedimento VALUES ('Hepatite C (Carga Viral e Tipagem)');
INSERT INTO imecare_procedimento VALUES ('Hepatite C por P.C.R. (Carga Viral)');
INSERT INTO imecare_procedimento VALUES ('Hepatite C por PCR (Detecção e Tipagem)');
INSERT INTO imecare_procedimento VALUES ('Hepatite D (Anti HDV)');
INSERT INTO imecare_procedimento VALUES ('Herpes tipo I IgG');
INSERT INTO imecare_procedimento VALUES ('Herpes tipo I IgM');
INSERT INTO imecare_procedimento VALUES ('Herpes tipo II IgG');
INSERT INTO imecare_procedimento VALUES ('Herpes tipo II IgM');
INSERT INTO imecare_procedimento VALUES ('HGH (Hormônio do Crescimento)');
INSERT INTO imecare_procedimento VALUES ('Hidatidose');
INSERT INTO imecare_procedimento VALUES ('Hidroxiprolina');
INSERT INTO imecare_procedimento VALUES ('Histoplasma');
INSERT INTO imecare_procedimento VALUES ('HIV (Elisa)');
INSERT INTO imecare_procedimento VALUES ('HIV - Genotipagem');
INSERT INTO imecare_procedimento VALUES ('HIV 1/2 no Líquor');
INSERT INTO imecare_procedimento VALUES ('HLA - 27');
INSERT INTO imecare_procedimento VALUES ('Homocisteína');
INSERT INTO imecare_procedimento VALUES ('HPV - Captura Híbrida');
INSERT INTO imecare_procedimento VALUES ('HTLV 1 e 2 por Western Blot');
INSERT INTO imecare_procedimento VALUES ('HVA IgM, Anti');
INSERT INTO imecare_procedimento VALUES ('HVA Total, Anti');
INSERT INTO imecare_procedimento VALUES ('IgA');
INSERT INTO imecare_procedimento VALUES ('IgA Salivar');
INSERT INTO imecare_procedimento VALUES ('IgD');
INSERT INTO imecare_procedimento VALUES ('IgE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - A. ALTERNATA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - A. ELATIOR');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - A. FUMIgATOS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - A. LACTOALBUMINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - A. PISILOSTACHYA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - A. PUPILULANS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - A. TRIFIDEA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - A. VERDADEIRA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ABACATE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ABELHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ABÓBORA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ACÁCIA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ACARUS SIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AIPO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALFA-AMILASE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALFACE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALFENA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALGODÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALGODÃO SEM.');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALHO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-1)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-10)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-15)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-16)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-2)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-20)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-3)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-5)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ALIMENTOS (FX-7)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AMEIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AMEIXA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AMÊNDOA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AMENDOIM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AMOEIRA BRANCA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AMOXILINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AMPICILINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ANANÁS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ANIMAIS (EX-1)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ANIMAIS (EX-2)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ANIMAIS (EX-70)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ANIMAIS (EX-72)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ANIMAIS (EX-73)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ANISAKIS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ARENQUE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ARROZ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-1)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-2)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-3)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-4)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-5)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-6)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-7)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-8)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ÁRVORES (TX-9)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ASCARIS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ASPERGILLUS NIGER');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ATUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AVEIA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AVELÃ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AVELEIRA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AZEDINHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - AZEVEM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BABA DE BOI');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BANANA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BARATA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BATATA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BATATA DOCE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BETERRABA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - B-LACTOALBUMINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BLOMIA TROPICALIS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BORDO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BOTRYTIS CINEREA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BRÓCOLIS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - BROMUS INERMIS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - C. ACREMONIUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - C. HERBARUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - C. JARDIM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - C. LEWISI');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CACAU');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CAMARÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CANDIDA ALBICANS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CANIÇO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CANIÇO MOLHADO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARANGUEIJO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARNE DE CARNEIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARNE DE COELHO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARNE DE GALINHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARNE DE PERU');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARNE DE PORCO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARNE DE VACA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARVALHO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CARYA PECAN');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CASEÍNA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CASPA DE CÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CASPA DE CAVALO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CASPA DE GATO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CASPA DE VACA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CASTANHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CASUARINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CEBOLA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CEDRO JAPONÊS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CENOURA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CENTEIO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CEREJA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CEVADA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CHORAMINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CHORPO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CHUCHU');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CIPRESTE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CLARA DE OVO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - COCO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CORRIJÓ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - COUVE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - CURVULARIA LUNATA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - D. FARINAE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - D. MICROCERAS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - D. PTERONYSSINUS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - DAMASCO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - DENTE DE LEÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - E. PURPURANSCENS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ECHINOCOCCUS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVA DE FEBRA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVA FINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVA LANAR');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVAS DANINHAS (WX-1)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVAS DANINHAS (WX-2)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVAS DANINHAS (WX-3)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVAS DANINHAS (WX-5)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVAS DANINHAS (WX-6)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVAS DANINHAS (WX-7)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ERVILHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ESPINAFRE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ESPINHOSA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - EUCALIPTO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - EUROGLIPUS MAYNEI');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - EXCREMENTO DE PERIQUITO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - EXCREMENTO DE POMBO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - F. ACANTHICARPA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - F. MONILIFORME');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FAIA EUROPÉIA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FEIJÃO BRANCO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FENO DE CHEIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FICUS SP');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FOLHA DE TABACO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FORMALINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FORMIgA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FREIXO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FUNGOS (MX-1)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - FUNGOS (MX-2)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - G. DOMESTICUS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GEMA DE OVO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GIRASSOL');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GLÚTEN');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GRAMA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GRAMÍNEAS (GX-1)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GRAMÍNEAS (GX-2)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GRAMÍNEAS (GX-3)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GRAMÍNEAS (GX-4)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GRÃO DE CAFÉ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - GRÃO DE SOJA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - H. HALODES');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - INSULINA BOVINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - INSULINA HUMANA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - INSULINA SUÍNA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ISOCIANATO HDI');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ISOCIANATO MDI');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ISOCIANATO TDI');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ISPAGULA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - IVA CILIATA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - KIWI');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LAGOSTA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LARANJA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LARVA DE SANGUE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LASNA SINTRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LÁTEX');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LEITE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LEITE FERVIDO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LENTILHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LEVEDURA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LIMÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - LULA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - M. LEUCADENDRON');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - M. RACEMOSUS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MAÇÃ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MALTE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MAMÃO PAPAYA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MANGA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MARACUJÁ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MARGARIDA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MELANCIA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MELÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MEXILHÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MEXILHÃO AZUL');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MILHO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MILHO COMUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MILHO JAPÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MILHO MOÍDO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MORANGA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MORANGO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MOSCA DE CAVALO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MOSCARDO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MOSCARDO AMARELO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MOSQUITO COMUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - MOSTARDA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - NA. FETÁLICO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - NA. TRIMELI.');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - NOGUEIRA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - NOZ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - NOZ CAJÚ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - NOZ DE PEÇÃ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - NOZ DO BRASIL');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - Ó. DE ETILENO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OCUPACIONAIS (PAX-1)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OCUPACIONAIS (PAX-2)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OCUPACIONAIS (PAX-3)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OCUPACIONAIS (PAX-4)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OCUPACIONAIS (PAX-5)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OCUPACIONAIS (PAX-6)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OLIVEIRA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ORÉGANO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OSTRA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OVO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OVO ALBUMINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OVO MUCÓIDE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - OXECEDRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - P. ARUNDINÁCEA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - P. JUDAICA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - P. JULIFORA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - P. NOTATUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - P. ORBICULARE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PANASCO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÁPRICA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PARIETARIA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PASPALUM NOTATUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÉ DE GANSO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PEIXE (Bacalhau)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE CABRA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE CANEIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE CÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE COBAIA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE COELHO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE HAMSTER');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE PORCO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE RATAZANA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊLO DE RATO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENA DE CANÁRIO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENA DE GALINHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENA DE GANSO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENA DE PAPAGAIO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENA DE PATO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENA DE PERIQUITO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENA DE PERU');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENAS (EX-71)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENICILINA G');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PENICILINA V');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PERA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÊSSEGO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PHOMA BETAE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PIMENTA PRETA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PIMENTÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PINHEIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PISTACHO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PLÁTANO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÓ (HX-2)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PÓ CASEIRO (HX-1)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - POLVO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - PULGA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - QUEIJO (CAMB.)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - QUEIJO (CHEDDAR)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - R. DE BAMBÚ');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - R. NIGRICANS');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - RABO DE GATO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - RABO DE RAPOSA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - RATAZANA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - RATINHO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - S. BOTRUOSUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - S. BRAVA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - S. CASTOR');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - S. SÉSAMO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SALGADEIRA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SALGUEIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SALMÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SALSA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SARDA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SARDINHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SARGASSO BRAVO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SEDA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SOLHA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SORO DE PERIQUITO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SORO DE RATAZANA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SORO DE RATO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - SULFAMETHOXAZOL (C233)');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - T. ANGUSTUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - T. MOURISCO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - T. PUTRECESNTIAE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TANGERINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TARTRAZINA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TILIA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TOMATE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TORANJA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TRAÇA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TRICHONEMA PALLIUM');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TRIGO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - TRUTA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ULMEIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - URINA DE RATO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - URTIGÃO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - UVA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - VARVERDE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - VESPA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - VESPA DO PAPEL');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - VESPA EUROPÉIA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - VIDOEIRO');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - VISGAUREA');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - X. COMMUNE');
INSERT INTO imecare_procedimento VALUES ('IgE Específico - ZABURRO DE ALEPO');
INSERT INTO imecare_procedimento VALUES ('IGF - 3');
INSERT INTO imecare_procedimento VALUES ('IgG');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - A. LACTOALBUMINA');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - ALIMENTOS (FX-5)');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - AMENDOIM');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - AMOXICILINA');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - ARROZ');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - AVEIA');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - BANANA');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - B-LACTOALBUMINA');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - CASEINA');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - CLARA DE OVO');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - FEIJÃO');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - FRANGO');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - GADO');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - GEMA DE OVO');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - LEITE');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - MILHO');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - PENICILINA');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - PENICILINA V');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - SOJA');
INSERT INTO imecare_procedimento VALUES ('IgG Específico - TRIGO');
INSERT INTO imecare_procedimento VALUES ('IgG no Líquor');
INSERT INTO imecare_procedimento VALUES ('IgG Sub-classe 1');
INSERT INTO imecare_procedimento VALUES ('IgG Sub-classe 2');
INSERT INTO imecare_procedimento VALUES ('IgG Sub-classe 3');
INSERT INTO imecare_procedimento VALUES ('IgG Sub-classe 4');
INSERT INTO imecare_procedimento VALUES ('IgM');
INSERT INTO imecare_procedimento VALUES ('IgM no Líquor');
INSERT INTO imecare_procedimento VALUES ('Imunoclomplexos Circulantes');
INSERT INTO imecare_procedimento VALUES ('Imunofenotipagem do Sangue Periférico');
INSERT INTO imecare_procedimento VALUES ('Imunoglobulinas por Eletroforese');
INSERT INTO imecare_procedimento VALUES ('Índice de Katz');
INSERT INTO imecare_procedimento VALUES ('Índice de Saturação da Transferrina');
INSERT INTO imecare_procedimento VALUES ('Índice de Tiroxina Livre (ITL)');
INSERT INTO imecare_procedimento VALUES ('Insulina');
INSERT INTO imecare_procedimento VALUES ('Insulina - Anticorpos Anti');
INSERT INTO imecare_procedimento VALUES ('Insulina (Horário)');
INSERT INTO imecare_procedimento VALUES ('Insulina Pós-Prandial');
INSERT INTO imecare_procedimento VALUES ('JO-1 Anticorpos Anti');
INSERT INTO imecare_procedimento VALUES ('Lactose - Pesquisa (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Legionella IgG');
INSERT INTO imecare_procedimento VALUES ('Legionella IgM');
INSERT INTO imecare_procedimento VALUES ('Leptina');
INSERT INTO imecare_procedimento VALUES ('Leptospirose (Urina)');
INSERT INTO imecare_procedimento VALUES ('Leptospirose IgG (Soro)');
INSERT INTO imecare_procedimento VALUES ('Leptospirose IgM (Soro)');
INSERT INTO imecare_procedimento VALUES ('Leucócitos Fecais');
INSERT INTO imecare_procedimento VALUES ('Leucograma');
INSERT INTO imecare_procedimento VALUES ('Leveduras, Pesquisa de');
INSERT INTO imecare_procedimento VALUES ('LH - Luteinizante - Pool');
INSERT INTO imecare_procedimento VALUES ('LH (Luteinizante)');
INSERT INTO imecare_procedimento VALUES ('Linfócitos - Tipagem');
INSERT INTO imecare_procedimento VALUES ('Lipase');
INSERT INTO imecare_procedimento VALUES ('Lipídios Totais');
INSERT INTO imecare_procedimento VALUES ('Lipidograma (Eletroforese Lipoproteína)');
INSERT INTO imecare_procedimento VALUES ('Lipoproteína A');
INSERT INTO imecare_procedimento VALUES ('Líquor - Citológico');
INSERT INTO imecare_procedimento VALUES ('Listéria');
INSERT INTO imecare_procedimento VALUES ('Lítio');
INSERT INTO imecare_procedimento VALUES ('Lítio Eritrocitário');
INSERT INTO imecare_procedimento VALUES ('Lítio Ratio');
INSERT INTO imecare_procedimento VALUES ('Maconha (Imunocromatografia)');
INSERT INTO imecare_procedimento VALUES ('Magnésio');
INSERT INTO imecare_procedimento VALUES ('Magnésio (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('Magnésio Eritrocitário');
INSERT INTO imecare_procedimento VALUES ('Malária (Pesquisa)');
INSERT INTO imecare_procedimento VALUES ('Manganês (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Manganês (Urina)');
INSERT INTO imecare_procedimento VALUES ('Melatonina');
INSERT INTO imecare_procedimento VALUES ('Mercúrio (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Mercúrio (Urina)');
INSERT INTO imecare_procedimento VALUES ('Metahemoglobina');
INSERT INTO imecare_procedimento VALUES ('Metanefrinas Plasmática');
INSERT INTO imecare_procedimento VALUES ('Metanefrinas Urinárias');
INSERT INTO imecare_procedimento VALUES ('Metanol');
INSERT INTO imecare_procedimento VALUES ('Metil Etil Cetona');
INSERT INTO imecare_procedimento VALUES ('Micoplasma Pneumoniae IgG');
INSERT INTO imecare_procedimento VALUES ('Micoplasma Pneumoniae IgM');
INSERT INTO imecare_procedimento VALUES ('Microalbuminúria');
INSERT INTO imecare_procedimento VALUES ('Microalbuminúria (Amostra)');
INSERT INTO imecare_procedimento VALUES ('Microssomais, Anti');
INSERT INTO imecare_procedimento VALUES ('Mioglobina Urinária');
INSERT INTO imecare_procedimento VALUES ('Mitocôndria, Anticorpos Anti');
INSERT INTO imecare_procedimento VALUES ('Monoteste');
INSERT INTO imecare_procedimento VALUES ('Mucoproteínas');
INSERT INTO imecare_procedimento VALUES ('N - Metilformamida');
INSERT INTO imecare_procedimento VALUES ('Netilmicina');
INSERT INTO imecare_procedimento VALUES ('Níquel (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Níquel (Urina)');
INSERT INTO imecare_procedimento VALUES ('Nitrazepan');
INSERT INTO imecare_procedimento VALUES ('Osmolalidade');
INSERT INTO imecare_procedimento VALUES ('Osmolaridade');
INSERT INTO imecare_procedimento VALUES ('Osteocalcina');
INSERT INTO imecare_procedimento VALUES ('Oxcarbazepina');
INSERT INTO imecare_procedimento VALUES ('Oxiurus, Pesquisa');
INSERT INTO imecare_procedimento VALUES ('Painel de Minerais');
INSERT INTO imecare_procedimento VALUES ('P-Aminofenol');
INSERT INTO imecare_procedimento VALUES ('Paratormônio - PTH');
INSERT INTO imecare_procedimento VALUES ('Paternidade por DNA Duo, Teste Judicial');
INSERT INTO imecare_procedimento VALUES ('Paternidade por DNA Duo, Teste Particular');
INSERT INTO imecare_procedimento VALUES ('Paternidade por DNA Trio, Teste Judicial');
INSERT INTO imecare_procedimento VALUES ('Paternidade por DNA Trio, Teste Particular');
INSERT INTO imecare_procedimento VALUES ('Paul Bunnel Davidsohn');
INSERT INTO imecare_procedimento VALUES ('Peptídeo Natriurético Cerebral');
INSERT INTO imecare_procedimento VALUES ('Peptídeo C');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Giárdia');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Albumina');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Campilobacter sp');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Cetonúria');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Eschericia Coli Patogênica');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Esperma (Urina)');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Larvas');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Linfócitos Atípicos');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Neisseria');
INSERT INTO imecare_procedimento VALUES ('Pesquisa de Yersinia');
INSERT INTO imecare_procedimento VALUES ('PH Fecal');
INSERT INTO imecare_procedimento VALUES ('PH Urinário');
INSERT INTO imecare_procedimento VALUES ('Planoteste');
INSERT INTO imecare_procedimento VALUES ('Plaquetas');
INSERT INTO imecare_procedimento VALUES ('Pólio, Anti');
INSERT INTO imecare_procedimento VALUES ('Porfobilinogênio');
INSERT INTO imecare_procedimento VALUES ('Potássio');
INSERT INTO imecare_procedimento VALUES ('Potássio Urinário');
INSERT INTO imecare_procedimento VALUES ('Pré-Albumina');
INSERT INTO imecare_procedimento VALUES ('Pregnandiol');
INSERT INTO imecare_procedimento VALUES ('Primidona');
INSERT INTO imecare_procedimento VALUES ('Produto de Degradação da Fibrina');
INSERT INTO imecare_procedimento VALUES ('Progesterona');
INSERT INTO imecare_procedimento VALUES ('Progesterona Pool');
INSERT INTO imecare_procedimento VALUES ('Prolactina');
INSERT INTO imecare_procedimento VALUES ('Prolactina Pool');
INSERT INTO imecare_procedimento VALUES ('Proteína C');
INSERT INTO imecare_procedimento VALUES ('Proteína de Bence Jones');
INSERT INTO imecare_procedimento VALUES ('Proteína S');
INSERT INTO imecare_procedimento VALUES ('Proteína-C Reativa');
INSERT INTO imecare_procedimento VALUES ('Proteína-C Reativa (UltraSensível)');
INSERT INTO imecare_procedimento VALUES ('Proteínas Totais');
INSERT INTO imecare_procedimento VALUES ('Proteinograma');
INSERT INTO imecare_procedimento VALUES ('Proteinograma na Urina');
INSERT INTO imecare_procedimento VALUES ('Proteinograma no Líquor');
INSERT INTO imecare_procedimento VALUES ('Proteinúria (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('Proteinúria (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Prova do Laço');
INSERT INTO imecare_procedimento VALUES ('PSA Livre');
INSERT INTO imecare_procedimento VALUES ('PSA Total');
INSERT INTO imecare_procedimento VALUES ('Quinidina');
INSERT INTO imecare_procedimento VALUES ('Receptores Hormonais');
INSERT INTO imecare_procedimento VALUES ('Renina');
INSERT INTO imecare_procedimento VALUES ('Reticulócitos');
INSERT INTO imecare_procedimento VALUES ('Retração do Coágulo');
INSERT INTO imecare_procedimento VALUES ('RNA, Anticorpos Anti');
INSERT INTO imecare_procedimento VALUES ('RNP, Auto Anticorpos Antinucleares - Anti');
INSERT INTO imecare_procedimento VALUES ('Rotavírus, Pesquisa de');
INSERT INTO imecare_procedimento VALUES ('Rubéola IgG');
INSERT INTO imecare_procedimento VALUES ('Rubéola IgM');
INSERT INTO imecare_procedimento VALUES ('Saccharomyces Cerevisiae Anticorpos Totais');
INSERT INTO imecare_procedimento VALUES ('Sangue Oculto');
INSERT INTO imecare_procedimento VALUES ('Sangue Oculto Monoclonal');
INSERT INTO imecare_procedimento VALUES ('Sarampo IgG');
INSERT INTO imecare_procedimento VALUES ('Sarampo IgM');
INSERT INTO imecare_procedimento VALUES ('SCL 70 - Auto Anticorpos Anti');
INSERT INTO imecare_procedimento VALUES ('Sedimento Urinário');
INSERT INTO imecare_procedimento VALUES ('Sedimento Urinário - Hamburger (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Selênio');
INSERT INTO imecare_procedimento VALUES ('Serotonina Total');
INSERT INTO imecare_procedimento VALUES ('SHBG');
INSERT INTO imecare_procedimento VALUES ('Sódio');
INSERT INTO imecare_procedimento VALUES ('Sódio (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('Sódio (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Somatomedina C ou IGF-1');
INSERT INTO imecare_procedimento VALUES ('Substâncias Redutoras nas Fezes');
INSERT INTO imecare_procedimento VALUES ('Sulfato de Deidroepiandrosterona (S-DHEA)');
INSERT INTO imecare_procedimento VALUES ('T3 (Triiodotironina)');
INSERT INTO imecare_procedimento VALUES ('T3 Captação');
INSERT INTO imecare_procedimento VALUES ('T3 Livre - Triiodotironina Livre');
INSERT INTO imecare_procedimento VALUES ('T4 (Tiroxina)');
INSERT INTO imecare_procedimento VALUES ('T4 Livre');
INSERT INTO imecare_procedimento VALUES ('Tempo de Coagulação');
INSERT INTO imecare_procedimento VALUES ('Tempo de Protrombina');
INSERT INTO imecare_procedimento VALUES ('Tempo de Sangria');
INSERT INTO imecare_procedimento VALUES ('Tempo de Tromboplastina Parcial');
INSERT INTO imecare_procedimento VALUES ('Teofilina');
INSERT INTO imecare_procedimento VALUES ('Teste da Sacarose');
INSERT INTO imecare_procedimento VALUES ('Teste de Falcização');
INSERT INTO imecare_procedimento VALUES ('Teste de Ham');
INSERT INTO imecare_procedimento VALUES ('Teste do Pezinho - Ampliado');
INSERT INTO imecare_procedimento VALUES ('Teste do Pezinho - Básico');
INSERT INTO imecare_procedimento VALUES ('Teste do Pezinho - Master');
INSERT INTO imecare_procedimento VALUES ('Teste do Pezinho - Plus');
INSERT INTO imecare_procedimento VALUES ('Testosterona');
INSERT INTO imecare_procedimento VALUES ('Testosterona Livre');
INSERT INTO imecare_procedimento VALUES ('Testosterona Pool');
INSERT INTO imecare_procedimento VALUES ('TGO');
INSERT INTO imecare_procedimento VALUES ('TGP');
INSERT INTO imecare_procedimento VALUES ('Tireoglobulina');
INSERT INTO imecare_procedimento VALUES ('Tirosina (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Toxocara Canis, Anticorpos Anti IgG + IgM');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose Avidez IgG');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgA');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgG (Elisa)');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgG (Hemoaglutinação)');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgG (Imuno e Elfa)');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgG (Líquor)');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgG Captura');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgM (Elisa)');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgM (Hemoaglutinação)');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgM (Imuno e Elfa)');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgM (Líquor)');
INSERT INTO imecare_procedimento VALUES ('Toxoplasmose IgM Captura');
INSERT INTO imecare_procedimento VALUES ('TPO, Anti');
INSERT INTO imecare_procedimento VALUES ('TRAB-Anticorpos Inibidores do TSH');
INSERT INTO imecare_procedimento VALUES ('Transferrina');
INSERT INTO imecare_procedimento VALUES ('Transglutaminase Tisular IgA, Ac. Anti');
INSERT INTO imecare_procedimento VALUES ('Triclorocompostos');
INSERT INTO imecare_procedimento VALUES ('Triglicerídios');
INSERT INTO imecare_procedimento VALUES ('Tripsina Sérica');
INSERT INTO imecare_procedimento VALUES ('Trombina, Tempo');
INSERT INTO imecare_procedimento VALUES ('Troponina I');
INSERT INTO imecare_procedimento VALUES ('TSH Ultra Sensível');
INSERT INTO imecare_procedimento VALUES ('Uréia');
INSERT INTO imecare_procedimento VALUES ('Uréia (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('Uréia Pós Diálise');
INSERT INTO imecare_procedimento VALUES ('Uricosúria (Urina 24 H)');
INSERT INTO imecare_procedimento VALUES ('Uricosúria (Urina Amostra)');
INSERT INTO imecare_procedimento VALUES ('Urocultura');
INSERT INTO imecare_procedimento VALUES ('Urocultura (1º Jato)');
INSERT INTO imecare_procedimento VALUES ('Uroporfirina');
INSERT INTO imecare_procedimento VALUES ('Vancomicina');
INSERT INTO imecare_procedimento VALUES ('Varicela Zoster IgG');
INSERT INTO imecare_procedimento VALUES ('Varicela Zoster IgM');
INSERT INTO imecare_procedimento VALUES ('VDRL');
INSERT INTO imecare_procedimento VALUES ('Vírus Influenza');
INSERT INTO imecare_procedimento VALUES ('Vitamina A');
INSERT INTO imecare_procedimento VALUES ('Vitamina B 12');
INSERT INTO imecare_procedimento VALUES ('Vitamina B1');
INSERT INTO imecare_procedimento VALUES ('Vitamina B6');
INSERT INTO imecare_procedimento VALUES ('Vitamina D3');
INSERT INTO imecare_procedimento VALUES ('Vitamina E');
INSERT INTO imecare_procedimento VALUES ('VSG');
INSERT INTO imecare_procedimento VALUES ('Waaler-Rose');
INSERT INTO imecare_procedimento VALUES ('Widal');
INSERT INTO imecare_procedimento VALUES ('Zinco (Eritrocitário)');
INSERT INTO imecare_procedimento VALUES ('Zinco (Sangue)');
INSERT INTO imecare_procedimento VALUES ('Zinco (Urina)');